version: '3'
services:
  influxdb:
    restart: always
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - './data/influxdb:/var/lib/influxdb'
  grafana:
    restart: always
    image: grafana/grafana
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - './data/grafana:/var/lib/grafana'
    depends_on:
      - influxdb
  sensor:
    build: .
    restart: always
    depends_on:
      - influxdb
    devices:
      - "/dev/serial0:/dev/serial0"
